AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*
    - config/unicorn.rb
    - config/unicorn_staging.rb
    - tmp/**/*

##################### Style ##################################

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

##################### Metrics ##################################

# 30 まではギリギリ許せる範囲だった
Metrics/AbcSize:
  Max: 30

# 6 は強すぎるので緩める
Metrics/CyclomaticComplexity:
  Max: 10

# * 警告 120文字
# * 禁止 160文字
# のイメージ
Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

# 20 行超えるのは migration ファイル以外滅多に無い
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

# 分岐の数。ガード句を多用しているとデフォルト 7 だと厳しい
Metrics/PerceivedComplexity:
  Max: 8