version: '3'

services:
  web:
    build: .
    ports:
      - "80:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV:           $RAILS_ENV
      MYSQL_USER:          $MYSQL_USER
      MYSQL_PASSWORD:      $MYSQL_PASSWORD
      MYSQL_HOST:          $MYSQL_HOST
      MYSQL_DATABASE:      $MYSQL_DATABASE
      RAILS_SERVE_STATIC_FILES: "true"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql
volumes:
  bundle:
  mysql_data: