version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV:           development
      MYSQL_USER:          root
      MYSQL_PASSWORD:      password
      MYSQL_HOST:          db
      MYSQL_DATABASE:      app_development
      RAILS_SERVE_STATIC_FILES: "true"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
    ports:
      - '4306:3306'
    volumes:
      - ./db:/var/lib/mysql
volumes:
  bundle:
  mysql_data: